(async()=>{
 const wait=async(fn,ms=25000)=>{const end=Date.now()+ms;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+fn.toString())};
 const sidebarFingerprint=()=>{const pick=(selector)=>{const r=document.querySelector(selector).getBoundingClientRect();return [r.left,r.top,r.width,r.height]};return {sidebar:pick('#global-sidebar'),brand:pick('.brand-companion'),nav:pick('#global-sidebar nav .nav-item'),card:pick('#global-sidebar>div:last-child'),main:pick('#desktop-shell>main')}};
 const brandTextFingerprint=()=>{const pick=(element)=>{const r=element.getBoundingClientRect(),s=getComputedStyle(element);return [r.left,r.top,r.width,r.height,parseFloat(s.fontSize),Number(s.fontWeight)]};return {title:pick(document.querySelector('#global-sidebar .brand strong,#global-sidebar>div:first-child>div:first-child h2')),subtitle:pick(document.querySelector('#global-sidebar .brand small,#global-sidebar>div:first-child>div:first-child p'))}};
 const sameFingerprint=(a,b)=>Object.keys(a).every(key=>a[key].every((value,index)=>Math.abs(value-b[key][index])<=1));
 const sameSidebarStructure=(a,b)=>['sidebar','brand','nav','main'].every(key=>a[key].every((value,index)=>Math.abs(value-b[key][index])<=1));
 try{
  await wait(()=>state&&document.documentElement.dataset.ready==='true');
  if(page!=='settings'){
   if(!document.querySelector('#global-sidebar').textContent.includes('蟑螂强'))throw Error('Brand missing');
   if(document.querySelectorAll('#global-sidebar nav button').length!==7)throw Error('Navigation incomplete');
   if(document.querySelectorAll('#global-sidebar .nav-icon svg').length!==7)throw Error('Unified sidebar icons missing');
   const inactiveNav=document.querySelector('#global-sidebar .nav-item:not([aria-current])'),navStyle=getComputedStyle(inactiveNav);if(parseFloat(navStyle.borderTopWidth)!==0||navStyle.backgroundColor==='rgb(255, 255, 255)')throw Error('Sidebar styling diverged');
   const companion=document.querySelector('.brand-companion').getBoundingClientRect();if(Math.abs(companion.width-48)>1||Math.abs(companion.height-48)>1)throw Error('Brand size diverged');
   const taskButton=document.querySelector('#global-sidebar .coral-pill'),taskStyle=getComputedStyle(taskButton);if(parseFloat(taskStyle.borderTopWidth)!==0)throw Error('Sidebar task button border returned');
    await wait(()=>document.querySelector('.titlebar-logo')?.complete&&document.querySelector('.titlebar-logo')?.naturalWidth>0&&document.querySelector('.brand-companion')?.complete&&document.querySelector('.brand-companion')?.naturalWidth>0);
   if(document.body.scrollWidth>innerWidth+2)throw Error('Horizontal overflow');
   const bar=document.querySelector('#window-bar'),buttons=Array.from(bar.querySelectorAll(':scope > button'));if(buttons.length!==3)throw Error('Window controls missing');const barCenter=bar.getBoundingClientRect().top+bar.getBoundingClientRect().height/2;for(const button of buttons){const rect=button.getBoundingClientRect();if(Math.abs(rect.top+rect.height/2-barCenter)>1)throw Error('Window control is not vertically centered');if(rect.width!==48||rect.height!==40)throw Error('Window control spacing changed')}
  }
  if(page==='conversion'){
   localStorage.setItem('referenceSidebarFingerprint',JSON.stringify(sidebarFingerprint()));
   await wait(()=>state.conversion.items.length===1);document.querySelector('#queue .queue-row').click();
   const progress=document.querySelector('#live-progress'),status=document.querySelector('#live-status'),progressBox=document.querySelector('.conversion-progress');const progressRect=progress.getBoundingClientRect(),statusRect=status.getBoundingClientRect(),boxRect=progressBox.getBoundingClientRect();if(progress.nextElementSibling!==status||statusRect.top<progressRect.bottom-1)throw Error('Footer status is not below progress');if(statusRect.left<boxRect.left-1||statusRect.right>boxRect.right+1||status.scrollWidth<status.clientWidth)throw Error('Footer status overflow containment failed');if(status.title!==state.conversion.status)throw Error('Full footer status tooltip missing');
   const formatSelect=document.querySelector('#format'),sizeSelect=document.querySelector('#size'),sizeFields=document.querySelector('#custom-size-fields'),prefixSelect=document.querySelector('#namePrefix');if(formatSelect.getBoundingClientRect().width<179||sizeSelect.getBoundingClientRect().width<149||prefixSelect.getBoundingClientRect().width<99)throw Error('Select width collapsed');if(sizeSelect.getBoundingClientRect().right>sizeFields.getBoundingClientRect().left-6)throw Error('Output size controls overlap');if(parseFloat(getComputedStyle(formatSelect).paddingRight)<39||parseFloat(getComputedStyle(sizeSelect).paddingRight)<34||parseFloat(getComputedStyle(prefixSelect).paddingRight)<30)throw Error('Select arrow clearance missing');
   for(const id of ['customNameEnabled','namePrefix','nameSuffix','name-preview'])if(!document.querySelector('#'+id))throw Error('Custom naming control missing: '+id);
   const checkboxThemes={classic:'rgb(255, 87, 34)',cyber:'rgb(16, 185, 129)',minimal:'rgb(24, 24, 27)',industrial:'rgb(245, 158, 11)',mediterranean:'rgb(242, 142, 19)',retro:'rgb(230, 57, 70)',liquidCrystal:'rgb(255, 87, 34)'},originalTheme=document.documentElement.dataset.theme,checkboxes=['sameFolder','customNameEnabled','alpha','openFolder'].map(id=>document.querySelector('#'+id)).concat(document.querySelector('#queue input[type=checkbox]'),document.querySelector('[data-action=checkAll]'));if(checkboxes.some(box=>!box))throw Error('Checkbox controls missing');const originalChecked=checkboxes.map(box=>box.checked);checkboxes.forEach(box=>box.checked=true);for(const [theme,expectedColor] of Object.entries(checkboxThemes)){window.PngToJpgTheme.apply(theme,false);for(const box of checkboxes){const style=getComputedStyle(box);if(style.backgroundColor!==expectedColor||style.backgroundImage==='none')throw Error(theme+' checked checkbox mark is not visible')}}window.PngToJpgTheme.apply(originalTheme,false);checkboxes.forEach((box,index)=>box.checked=originalChecked[index]);
   document.querySelector('#customNameEnabled').checked=true;prefixSelect.value='副图';prefixSelect.dispatchEvent(new Event('change',{bubbles:true}));if(document.querySelector('#nameSuffix').value!=='2'||!document.querySelector('#name-preview').textContent.includes('副图2'))throw Error('Secondary image default suffix failed');document.querySelector('#nameSuffix').value='8';document.querySelector('#nameSuffix').dispatchEvent(new Event('change',{bubbles:true}));if(document.querySelector('#nameSuffix').value!=='8')throw Error('Manual custom suffix was overwritten');prefixSelect.value='A';prefixSelect.dispatchEvent(new Event('change',{bubbles:true}));if(document.querySelector('#nameSuffix').value!=='1'||!document.querySelector('#name-preview').textContent.includes('A1'))throw Error('A default suffix failed');prefixSelect.value='主图';prefixSelect.dispatchEvent(new Event('change',{bubbles:true}));if(document.querySelector('#nameSuffix').value!=='1'||!document.querySelector('#name-preview').textContent.includes('主图1'))throw Error('Main image default suffix failed');
   document.querySelector('#format').value='png';document.querySelector('#size').value='4';document.querySelector('#width').value=64;document.querySelector('#height').value=64;
   document.querySelector('#sameFolder').checked=true;document.querySelector('#openFolder').checked=false;document.querySelector('[data-action=start]').click();
   await wait(()=>state.conversion.items.some(x=>/完成|成功/.test(x.status))&&!state.conversion.busy);
   await wait(()=>!!state.conversion.result);
   if(state.clarity.items.length!==1)throw Error('Queue isolation failed');
   if(state.conversion.width!==64||state.conversion.height!==64)throw Error('Size was not bound');
   document.querySelector('#format').value='pptx';
  }else if(page==='clarity'){
   if(!document.querySelector('[data-action=apiSettings]')||document.querySelector('[data-action=settings]')?.closest('.config-card'))throw Error('Clarity API configuration entry missing or still bound to preferences');
   document.querySelector('#mode').value='保守清晰';document.querySelector('#mode').dispatchEvent(new Event('change',{bubbles:true}));
   document.querySelector('#queue .queue-row').click();document.querySelector('#sameFolder').checked=true;document.querySelector('[data-action=start]').click();
   await wait(()=>!state.clarity.busy&&state.clarity.items.some(x=>/完成/.test(x.status)));await wait(()=>!!state.clarity.result);
   const compareViewport=document.querySelector('#compare-viewport');if(document.querySelector('#wipe-slider'))throw Error('Old comparison range slider still exists');
   document.querySelector('[data-action=sideBySide]').click();if(compareViewport.classList.contains('wipe')||document.querySelector('[data-action=sideBySide]').getAttribute('aria-pressed')!=='true')throw Error('Side-by-side compare mode failed');
   document.querySelector('[data-action=wipe]').click();if(!compareViewport.classList.contains('wipe')||document.querySelector('[data-action=wipe]').getAttribute('aria-pressed')!=='true')throw Error('Pointer compare mode failed');
   const compareRect=compareViewport.getBoundingClientRect();compareViewport.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:41,button:0,clientX:compareRect.left+compareRect.width*.25}));compareViewport.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:41,button:0,clientX:compareRect.left+compareRect.width*.7}));compareViewport.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:41,button:0,clientX:compareRect.left+compareRect.width*.7}));if(Math.abs(parseFloat(compareViewport.style.getPropertyValue('--wipe'))-70)>1)throw Error('Direct pointer comparison drag failed');
    const holdOriginal=document.querySelector('[data-action=holdOriginal]');holdOriginal.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:42,button:0}));if(!compareViewport.classList.contains('original-only')||holdOriginal.getAttribute('aria-pressed')!=='true')throw Error('Hold-original press failed');window.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:42,button:0}));if(compareViewport.classList.contains('original-only')||holdOriginal.getAttribute('aria-pressed')!=='false')throw Error('Hold-original release failed');
    const compareContainer=document.querySelector('#compare-container'),exitPreview=document.querySelector('[data-action=closeFullPreview]');if(!exitPreview)throw Error('Full preview exit button missing');document.querySelector('[data-action=fullPreview]').click();if(!compareContainer.classList.contains('expanded-preview')||getComputedStyle(exitPreview).display==='none')throw Error('Full preview did not expose exit button');exitPreview.click();if(compareContainer.classList.contains('expanded-preview'))throw Error('Full preview exit button failed');document.querySelector('[data-action=fullPreview]').click();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));if(compareContainer.classList.contains('expanded-preview'))throw Error('Escape did not close full preview');
    const zoomPercent=document.querySelector('#zoom-percent');if(!zoomPercent||zoomPercent.textContent!=='100%')throw Error('Zoom percentage missing');document.querySelector('[data-action=zoomIn]').click();if(zoomPercent.textContent!=='125%')throw Error('Zoom percentage did not increase');document.querySelector('[data-action=zoomOut]').click();if(zoomPercent.textContent!=='100%')throw Error('Zoom percentage did not decrease');
   const failureReason='测试 API 失败详情：HTTP 401 密钥无效';renderQueue({...state.clarity,items:[{name:'失败示例.png',checked:true,status:'失败（悬停查看原因）',reason:failureReason}]});const failureRow=document.querySelector('#queue .queue-row'),failureStatus=failureRow?.querySelector('td:last-child');if(failureRow?.title!==failureReason||failureStatus?.title!==failureReason)throw Error('Clarity failure hover detail missing');renderQueue(state.clarity);
   send('checkAll',{value:false});await wait(()=>state.clarity.items.every(x=>!x.checked));if(!state.conversion.items[0].checked)throw Error('Clarity selection changed conversion queue');send('checkAll',{value:true});
  }else if(page==='organizer'){
   localStorage.setItem('referenceOrganizerSidebarFingerprint',JSON.stringify(sidebarFingerprint()));
   localStorage.setItem('referenceBrandTextFingerprint',JSON.stringify(brandTextFingerprint()));
   if(!state.organizer.path.includes('MonitorFixture'))throw Error('Monitor not isolated');
   for(const id of ['organizerOpenSheet','organizerTargetScreenEnabled','organizerTargetScreen','organizerIsland'])if(!document.querySelector('#'+id))throw Error('Organizer option missing: '+id);
    for(const id of ['desktop-organize-scope','desktop-organizer-info-dialog','desktop-history-list','desktop-history-count'])if(!document.querySelector('#'+id))throw Error('Desktop organizer control missing: '+id);for(const action of ['desktopProductOrganize','desktopProductUndo','desktopOrganizerInfo'])if(!document.querySelector('[data-action='+action+']'))throw Error('Desktop organizer action missing: '+action);const organizeButton=document.querySelector('[data-action=desktopProductOrganize]'),infoButton=document.querySelector('[data-action=desktopOrganizerInfo]'),organizeRect=organizeButton.getBoundingClientRect(),infoRect=infoButton.getBoundingClientRect();if(infoRect.width<34||infoRect.height<34||infoRect.left-organizeRect.right>12||Math.abs((infoRect.top+infoRect.height/2)-(organizeRect.top+organizeRect.height/2))>2)throw Error('Desktop organizer info button is too small or not beside organize button');
    const desktopScope=document.querySelector('#desktop-organize-scope');if(desktopScope.value!=='left'||desktopScope.options.length!==4)throw Error('Desktop organizer should default to left with four scopes');desktopScope.value='center';desktopScope.dispatchEvent(new Event('change',{bubbles:true}));await wait(()=>state.organizer.desktopScope==='center');document.querySelector('[data-action=desktopOrganizerInfo]').click();if(!document.querySelector('#desktop-organizer-info-dialog').open||!document.querySelector('#desktop-organizer-info-dialog').textContent.includes('保存 30 天'))throw Error('Desktop organizer history explanation missing');document.querySelector('[data-action=dismissDesktopOrganizerInfo]').click();const historyRow=document.querySelector('.desktop-history-row');if(state.organizer.desktopHistory.length!==1||!historyRow||historyRow.dataset.recordId!==state.organizer.desktopHistory[0].Id||!historyRow.textContent.includes('编号 ABC123')||!historyRow.textContent.includes('恢复这次')||!document.querySelector('#desktop-history-count').textContent.includes('1 条'))throw Error('Desktop organizer 30-day history did not render as a clickable record');
   const targetScreen=document.querySelector('#organizerTargetScreen'),targetScreenToggle=document.querySelector('#organizerTargetScreenEnabled');if(!targetScreen.disabled)throw Error('Target screen selector should start disabled');targetScreenToggle.checked=true;targetScreen.value=state.organizer.screenCount>1?'2':'1';targetScreen.dispatchEvent(new Event('change',{bubbles:true}));await wait(()=>state.organizer.targetScreenEnabled&&state.organizer.targetScreen===Number(targetScreen.value));if(targetScreen.disabled)throw Error('Target screen selector did not enable');
   const startMonitor=document.querySelector('[data-action=organizerStart]');startMonitor.click();if(!startMonitor.classList.contains('is-starting')||!startMonitor.textContent.includes('正在启动'))throw Error('Organizer start did not show immediate feedback');await wait(()=>state.organizer.enabled);await wait(()=>getComputedStyle(startMonitor).backgroundColor==='rgb(16, 185, 129)');if(startMonitor.disabled||!startMonitor.classList.contains('is-active')||startMonitor.getAttribute('aria-pressed')!=='true'||!startMonitor.textContent.includes('监控已开启')||startMonitor.querySelector('.organizer-start-check').classList.contains('hidden'))throw Error('Organizer active confirmation is not visible');startMonitor.click();if(!document.querySelector('#toast').textContent.includes('已在运行'))throw Error('Repeated organizer start did not confirm current state');
   document.querySelector('[data-action=organizerStop]').click();await wait(()=>!state.organizer.enabled);if(startMonitor.classList.contains('is-active')||startMonitor.getAttribute('aria-pressed')!=='false'||!startMonitor.textContent.includes('启动自动监控'))throw Error('Organizer start button did not reset after stopping');
   document.querySelector('[data-action=spreadsheets]').click();if(!document.querySelector('#spreadsheet-dialog').open)throw Error('Spreadsheet dialog failed');document.querySelector('[data-action=dismissSheet]').click();
  }else if(page==='imageLink'){
   const reference=JSON.parse(localStorage.getItem('referenceOrganizerSidebarFingerprint')||'null'),sidebarCurrent=sidebarFingerprint();if(!reference||!sameSidebarStructure(reference,sidebarCurrent))throw Error('Image link sidebar geometry differs from organizer page: '+JSON.stringify({reference,current:sidebarCurrent}));
   const brandReference=JSON.parse(localStorage.getItem('referenceBrandTextFingerprint')||'null'),brandCurrent=brandTextFingerprint();if(!brandReference||!sameFingerprint(brandReference,brandCurrent))throw Error('Image link brand text differs from organizer page: '+JSON.stringify({reference:brandReference,current:brandCurrent}));
   const sidebar=document.querySelector('#global-sidebar').getBoundingClientRect(),navItem=document.querySelector('#global-sidebar .nav-item').getBoundingClientRect(),title=document.querySelector('.link-heading h1'),brand=document.querySelector('#global-sidebar .brand strong'),brandSub=document.querySelector('#global-sidebar .brand small'),navText=document.querySelector('#global-sidebar .nav-item'),headingNote=document.querySelector('.link-heading p');if(Math.abs(sidebar.width-256)>1||Math.abs(navItem.height-48)>1||parseFloat(getComputedStyle(title).fontSize)!==24||parseFloat(getComputedStyle(brand).fontSize)!==18||parseFloat(getComputedStyle(brandSub).fontSize)!==12||parseFloat(getComputedStyle(navText).fontSize)!==14||parseFloat(getComputedStyle(headingNote).fontSize)!==12)throw Error('Image link page visual scale differs from original pages');
   if(!state.imageLink.name||!state.imageLink.result?.Direct)throw Error('Image link fixture missing');
   const left=document.querySelector('.link-left');if(left.scrollHeight>left.clientHeight+2)throw Error('Image link controls overflow vertically');
   const privacy=document.querySelector('.privacy-note').getBoundingClientRect(),main=document.querySelector('.link-main').getBoundingClientRect();if(privacy.bottom>main.bottom+1)throw Error('Image link privacy note is clipped');
   if(document.querySelectorAll('[data-result]').length!==9)throw Error('Image link result rows incomplete');
   if(document.body.textContent.includes('邮箱代码'))throw Error('Email code should be removed');
   if(!state.imageLink.hasConfig||state.imageLink.limitReached||!document.querySelector('#link-usage').textContent.includes('安全额度剩余'))throw Error('R2 free quota state missing');
   document.querySelector('[data-action=openR2Config]').click();if(!document.querySelector('#r2-config-dialog').open||!document.querySelector('#link-account')||!document.querySelector('#link-secret-key'))throw Error('R2 configuration dialog failed');
   const accountField=document.querySelector('#link-account'),accessField=document.querySelector('#link-access-key'),secretField=document.querySelector('#link-secret-key');accountField.value='invalid';accessField.value='keep-access';secretField.value='keep-secret';document.querySelector('[data-action=imageLinkSaveConfig]').click();await wait(()=>document.querySelector('#toast').style.display==='block');if(accessField.value!=='keep-access'||secretField.value!=='keep-secret'||!document.querySelector('#r2-config-dialog').open)throw Error('Failed R2 save cleared credentials or closed dialog');document.querySelector('#r2-config-dialog').close();
   const resize=document.querySelector('#link-resize'),width=document.querySelector('#link-width');resize.checked=false;resize.dispatchEvent(new Event('change',{bubbles:true}));if(!width.disabled)throw Error('Resize fields should disable when resize is off');
   resize.checked=true;resize.dispatchEvent(new Event('change',{bubbles:true}));if(width.disabled)throw Error('Resize fields should enable when resize is on');
  }else if(page==='localSearch'){
   const reference=JSON.parse(localStorage.getItem('referenceOrganizerSidebarFingerprint')||'null'),sidebarCurrent=sidebarFingerprint();if(!reference||!sameSidebarStructure(reference,sidebarCurrent))throw Error('Local search sidebar geometry differs from organizer page: '+JSON.stringify({reference,current:sidebarCurrent}));
   const brandReference=JSON.parse(localStorage.getItem('referenceBrandTextFingerprint')||'null'),brandCurrent=brandTextFingerprint();if(!brandReference||!sameFingerprint(brandReference,brandCurrent))throw Error('Local search brand text differs from organizer page: '+JSON.stringify({reference:brandReference,current:brandCurrent}));
   const sidebar=document.querySelector('#global-sidebar').getBoundingClientRect(),navItem=document.querySelector('#global-sidebar .nav-item').getBoundingClientRect(),title=document.querySelector('.search-heading h1'),brand=document.querySelector('#global-sidebar .brand strong'),brandSub=document.querySelector('#global-sidebar .brand small'),navText=document.querySelector('#global-sidebar .nav-item'),headingNote=document.querySelector('.search-heading p');if(Math.abs(sidebar.width-256)>1||Math.abs(navItem.height-48)>1||parseFloat(getComputedStyle(title).fontSize)!==24||parseFloat(getComputedStyle(brand).fontSize)!==18||parseFloat(getComputedStyle(brandSub).fontSize)!==12||parseFloat(getComputedStyle(navText).fontSize)!==14||parseFloat(getComputedStyle(headingNote).fontSize)!==12)throw Error('Local search page visual scale differs from original pages');
   if(state.localSearch.results.length!==3)throw Error('Local search fixture missing');
   if(document.querySelectorAll('.search-result').length!==3)throw Error('Local search results did not render');
   if(document.querySelectorAll('[data-action=localSearchOpenFile]').length!==3)throw Error('Local search file actions missing');
   if(document.querySelector('[data-action=localSearchOpenFile]').textContent!=='打开文件夹')throw Error('Folder search action missing');
   const mode=document.querySelector('#search-mode');mode.value='image';mode.dispatchEvent(new Event('change',{bubbles:true}));if(document.querySelector('#image-search-fields').hidden||!document.querySelector('#number-search-fields').hidden)throw Error('Local search mode switch failed');const referencePreview=document.querySelector('#search-reference-preview');await wait(()=>!referencePreview.hidden&&referencePreview.complete&&referencePreview.naturalWidth>0);if(referencePreview.getBoundingClientRect().height<120||document.querySelector('.drop-icon').offsetParent!==null)throw Error('Uploaded reference image preview is missing or too small');
   if(!document.querySelector('#local-search-status').textContent.includes('找到 3 项'))throw Error('Local search status missing');
   renderLocalSearch({...state.localSearch,busy:true,progress:0,scanned:42,status:'正在比较第 42 张图片 · fixture.png',results:[]});if(!document.querySelector('#local-search-progress').classList.contains('is-indeterminate')||!document.querySelector('.search-spinner')||!document.querySelector('.search-actions').classList.contains('is-running'))throw Error('Local search activity indicator missing');renderLocalSearch(state.localSearch);
  }else if(page==='changelog'){
   await wait(()=>document.querySelectorAll('.release-card').length>0);
   if(!document.querySelector('#changelog-content').textContent.includes('v3.0.7'))throw Error('Current release missing');
  }else if(page==='preferences'){
   const reference=JSON.parse(localStorage.getItem('referenceOrganizerSidebarFingerprint')||'null'),sidebarCurrent=sidebarFingerprint();if(!reference||!sameSidebarStructure(reference,sidebarCurrent))throw Error('Preferences sidebar geometry differs from organizer page');
   const themeOptions=Array.from(document.querySelectorAll('[data-theme-option]'));if(themeOptions.length!==7||document.querySelector('[data-field]')||document.querySelector('#api-frame'))throw Error('Preferences theme choices are incomplete');
   if(!window.PngToJpgTheme||document.documentElement.dataset.theme!=='classic'||!themeOptions.find(x=>x.value==='classic')?.checked)throw Error('Default theme was not initialized');
   const expectedCanvas={classic:'rgb(235, 237, 240)',cyber:'rgb(18, 18, 20)',minimal:'rgb(247, 247, 248)',industrial:'rgb(231, 233, 236)',mediterranean:'rgb(232, 242, 244)',retro:'rgb(242, 232, 223)',liquidCrystal:'rgb(235, 241, 248)'};
   for(const [theme,canvas] of Object.entries(expectedCanvas)){const option=themeOptions.find(x=>x.value===theme);option.checked=true;option.dispatchEvent(new Event('change',{bubbles:true}));if(localStorage.getItem('pngToJpg.theme')!==theme||document.documentElement.dataset.theme!==theme||getComputedStyle(document.body).backgroundColor!==canvas)throw Error(theme+' theme did not apply or persist')}
   const liquid=themeOptions.find(x=>x.value==='liquidCrystal');liquid.checked=true;liquid.dispatchEvent(new Event('change',{bubbles:true}));await wait(()=>parent.document.documentElement.dataset.theme==='liquidCrystal'&&Array.from(parent.document.querySelectorAll('iframe')).every(frame=>frame.contentDocument.documentElement.dataset.theme==='liquidCrystal'));const liquidMain=document.querySelector('[data-purpose=primary-workspace]');if(getComputedStyle(document.body).backgroundImage==='none'||!getComputedStyle(liquidMain).backdropFilter.includes('blur(24px)')||getComputedStyle(liquidMain).color!=='rgb(15, 23, 42)')throw Error('Liquid Crystal glass material or text contrast missing');
   if(!document.querySelector('[data-action=settings][aria-current="page"]'))throw Error('Preferences navigation state missing');
  }else{
   for(const field of ['Protocol','Endpoint','Model','Prompt','AuthHeader','AuthPrefix','ImageField','TimeoutSeconds','ImageEncoding','ResponseType','ResponsePath','FieldsJson'])if(!document.querySelector('[data-field="'+field+'"]'))throw Error('API field missing: '+field);document.querySelector('[data-action=advanced]').click();
   if(document.querySelector('#advancedSettingsContent').hidden)throw Error('Advanced settings failed');
   document.querySelector('#apiKeyInput').value='local-ui-test-key';document.querySelector('[data-action=saveConfig]').click();await wait(()=>state.hasKey);document.querySelector('#apiKeyInput').value='';
  }
  send('uiCheck',{ok:true});
 }catch(e){send('uiCheck',{ok:false,detail:page+': '+e.message})}
})();








